services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
    - "8000:8080"
    depends_on:
      - catalogdb
    environment:
      - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
      - DatabaseSettings__DatabaseName=CatalogDb
      - DatabaseSettings__CollectionNameBrands=Brands
      - DatabaseSettings__CollectionNameTypes=Types
      - DatabaseSettings__CollectionNameProducts=Products


  catalogdb:
    image: mongo
    container_name: catalogdb
    ports:
     - "27017:27017"
    volumes:
     - catalogdata:/data/db

  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always
    ports:
    - "6379:6379"

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    ports:
    - "8001:8080"
    depends_on:
      - basketdb
    environment:
      - RedisCacheSettings__ConnectionString=basketdb:6379
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
     - 9000:9000
     - 9443:9443
    volumes:
      - portainer_data:/data

volumes:
 catalogdata:
 portainer_data:



