services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
    - "8000:8080"
    depends_on:
      - catalogdb
    environment:
      - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
      - DatabaseSettings__DatabaseName=CatalogDb
      - DatabaseSettings__CollectionNameBrands=Brands
      - DatabaseSettings__CollectionNameTypes=Types
      - DatabaseSettings__CollectionNameProducts=Products


  catalogdb:
    image: mongo
    container_name: catalogdb
    ports:
     - "27017:27017"
    volumes:
     - catalogdata:/data/db

  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always
    ports:
    - "6379:6379"
  discountdb:
    image: postgres:17
    container_name: discountdb
    environment:
    - POSTGRES_USER=Admin
    - POSTGRES_PASSWORD=Password@1
    - POSTGRES_DB=DiscountDb
    restart: always
    ports:
    - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Admin -d DiscountDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=Admin@Admin.com
      - PGADMIN_DEFAULT_PASSWORD=Password@1
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin



  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    ports:
    - "8001:8080"
    depends_on:
      - basketdb
    environment:
      - RedisCacheSettings__ConnectionString=basketdb:6379
      - "GrpcSettings__DiscountUrl=http://discount.api:8080"
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
     - 9000:9000
     - 9443:9443
    volumes:
      - portainer_data:/data

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=Admin;Password=Password@1;"
    container_name: discount.api
    depends_on:
       discountdb:
        condition: service_healthy
    ports:
     - 8002:8080
 

volumes:
 catalogdata:
 portainer_data:
 postgres_data:
 pgadmin_data:




